# Generated by Django 3.0.7 on 2020-07-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='static/dashboard/img/Avatars/default-avatar.png', upload_to='static/dashboard/img/Avatars/all_auth_avatar'),
        ),
    ]
