# Generated by Django 2.2.7 on 2020-06-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior', models.CharField(max_length=264)),
                ('junior', models.CharField(max_length=264)),
                ('ans1', models.CharField(max_length=1000)),
                ('ans2', models.CharField(max_length=1000)),
                ('ans3', models.CharField(max_length=1000)),
                ('ans4', models.CharField(max_length=1000)),
                ('ans5', models.CharField(max_length=1000)),
                ('ans6', models.CharField(max_length=1000)),
                ('ans7', models.CharField(max_length=1000)),
                ('ans8', models.CharField(max_length=1000)),
                ('ans9', models.CharField(max_length=1000)),
                ('ans10', models.CharField(max_length=1000)),
                ('ans11', models.CharField(max_length=1000)),
                ('ans12', models.CharField(max_length=1000)),
                ('ans13', models.CharField(max_length=1000)),
                ('ans14', models.CharField(max_length=1000)),
                ('ans15', models.CharField(max_length=1000)),
            ],
        ),
    ]
