# Generated by Django 3.0.7 on 2020-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_senior_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_users',
            name='name',
            field=models.CharField(default='NA', max_length=264),
        ),
    ]
