# Generated by Django 3.0.7 on 2020-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_senior_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_users',
            name='avatar',
            field=models.ImageField(default='static/dashboard/img/Avatars/default-avatar.png', upload_to='static/dashboard/img/Avatars'),
        ),
        migrations.AddField(
            model_name='senior_users',
            name='nick_name',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='senior_users',
            name='story_name',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='senior_users',
            name='tag_line',
            field=models.CharField(default='', max_length=264),
        ),
    ]
