# Generated by Django 2.2.7 on 2020-07-03 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200704_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablethree',
            name='senior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dashboard.senior_users'),
        ),
    ]
