# Generated by Django 2.2.7 on 2020-07-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200704_0334'),
        ('dashboard', '0007_auto_20200704_1602'),
    ]

    operations = [
    ]
