# Generated by Django 3.0.7 on 2020-07-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200704_1602'),
        ('dashboard', '0005_auto_20200704_0334'),
    ]

    operations = [
    ]
