# Generated by Django 3.0.7 on 2020-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_merge_20200704_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_users',
            name='email',
            field=models.CharField(default='b16000@students.iitmandi.ac.in', max_length=200),
        ),
    ]
