# Generated by Django 2.2.7 on 2020-07-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_merge_20200704_1750'),
        ('dashboard', '0009_auto_20200704_1941'),
    ]

    operations = [
    ]
