# Generated by Django 3.0.7 on 2020-07-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200704_1941'),
        ('dashboard', '0008_merge_20200704_1750'),
    ]

    operations = [
    ]
