# Generated by Django 3.0.7 on 2020-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_merge_20200705_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior_users',
            name='avatar',
            field=models.ImageField(default='static/dashboard/img/Avatars/sideways/background_removed.png', upload_to='static/dashboard/img/Avatars/sideways'),
        ),
    ]
