# Generated by Django 3.0.7 on 2020-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_senior_users_avatar_standing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablethree',
            name='ans1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans10',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans11',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans12',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans13',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans14',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans15',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans3',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans4',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans5',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans6',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans7',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans8',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='ans9',
            field=models.TextField(max_length=1000),
        ),
    ]
