# Generated by Django 3.0.7 on 2020-07-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200705_1726'),
        ('dashboard', '0010_merge_20200705_1444'),
    ]

    operations = [
    ]
