# Generated by Django 2.2.7 on 2020-07-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200705_1726'),
        ('dashboard', '0010_merge_20200705_1444'),
    ]

    operations = [
    ]
