# Generated by Django 3.0.7 on 2020-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20200712_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablethree',
            name='ghissu_meter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='phodu_meter',
            field=models.IntegerField(default=0),
        ),
    ]
