# Generated by Django 3.0.7 on 2020-07-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200713_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablethree',
            name='ans16',
            field=models.TextField(default='silly ans', max_length=1000),
        ),
    ]
